- name: Set up nginx upstream network
  shell: >
    docker network create nginx-upstream || echo

- name: Run nginx proxy
  shell: >
    docker rm --force nginx-proxy ;
    docker run --restart always --detach
    --name nginx-proxy --network nginx-upstream
    --publish 80:80
    --publish 443:443
    --volume /etc/nginx/certs
    --volume /etc/nginx/vhost.d
    --volume /usr/share/nginx/html
    --volume /var/run/docker.sock:/tmp/docker.sock:ro
    jwilder/nginx-proxy

- name: Run letsencrypt nginx companion
  shell: >
    docker rm --force nginx-proxy-letsencrypt ;
    docker run --restart always --detach
    --name nginx-proxy-letsencrypt --network nginx-upstream
    --volumes-from nginx-proxy
    --volume /var/run/docker.sock:/var/run/docker.sock:ro
    --volume /etc/acme.sh
    --env "DEFAULT_EMAIL=m.lyamets@innopolis.ru"
    jrcs/letsencrypt-nginx-proxy-companion
